#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
domain="subdomain.domain.tld"
password="123456789"
dnsip=$(dig +short @external.dns.provider.server $domain aaaa | tr -d '\n')
ipv6addr=$(ip -j -6 address show | jq -j -r '.[] | select(.ifname == "ens18") | .addr_info[] | select((.scope == "global") and (.prefixlen == 64) and (.local|test("fd00.")|not)) | .local')
if [ "$dnsip" != "$ipv6addr" ]; then
curl "https://dyndnscompliant.provider.tld/update?hostname=$domain&password=$password&myip=$ipv6addr"
fi
